name: pytorch3gpu
channels:
  - pytorch
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - cuda90=1.0=h6433d27_0
  - cudatoolkit=9.0=h13b8566_0
  - freetype=2.9.1=h8a8886c_0
  - intel-openmp=2018.0.3=0
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.2=py36h651fb7a_0
  - mkl_random=1.0.1=py36h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.14.5=py36h1b885b7_4
  - numpy-base=1.14.5=py36hdbf6ddf_4
  - olefile=0.45.1=py36_0
  - openssl=1.0.2o=h20670df_0
  - pillow=5.1.0=py36heded4f4_0
  - pip=10.0.1=py36_0
  - pycparser=2.18=py36_1
  - python=3.6.6=hc3d631a_0
  - pytorch=0.4.0=py36_cuda9.0.176_cudnn7.1.2_1
  - readline=7.0=ha6073c6_4
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - tk=8.6.7=hc745277_3
  - torchvision=0.2.1=py36_1
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - h5py==2.8.0
    - pandas==0.22.0
    - pyfasta==0.5.2
    - python-dateutil==2.7.3
    - pytz==2018.5
    - scipy==1.1.0
    - xgboost==0.72.1
prefix: /cellar/users/jpark/software/anaconda3/envs/pytorch3gpu

